version: '2.4'

services:
  frontend-bitcoin-nodejs:
    container_name: frontend-bitcoin-nodejs
    image: node:10.13.0-alpine
    working_dir: /app
    volumes:
      - .:/app
  frontend-bitcoin-nginx:
    container_name: frontend-bitcoin-nginx
    image: nginx:1.15-alpine
    volumes:
      - ./dist:/var/www/public
      - ./docker/nginx:/etc/nginx/conf.d

networks:
  default:
    external:
      name: my-blog
